# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/orderbook_socket/v1/orderbook.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/orderbook_socket/v1/orderbook.proto", :syntax => :proto3) do
    add_message "orderbook_socket.v1.Orderbook" do
      optional :pair, :string, 1
      repeated :bids, :message, 2, "orderbook_socket.v1.OrderbookItem"
      repeated :asks, :message, 3, "orderbook_socket.v1.OrderbookItem"
      optional :twenty_four_hour_volume, :double, 4
      optional :twenty_four_hour_low, :double, 5
      optional :twenty_four_hour_high, :double, 6
      optional :twenty_four_hour_change, :double, 7
      optional :last_trade_price, :double, 8
      optional :spread, :double, 9
      optional :twenty_four_hour_percent_change, :double, 10
      optional :twenty_four_hour_price_percent_change, :double, 11
    end
    add_message "orderbook_socket.v1.OrderbookItem" do
      optional :price, :double, 1
      optional :quantity, :double, 2
    end
  end
end

module OrderbookSocket
  module V1
    Orderbook = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("orderbook_socket.v1.Orderbook").msgclass
    OrderbookItem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("orderbook_socket.v1.OrderbookItem").msgclass
  end
end
